accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('emailsingup/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='accounts:login'), name='logout'),
]

src/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('user/', include('user.urls')),
    path('posts/', include('post.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.db import models
from .managers import CustomUserManager

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=150, unique=True,)
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=200, blank=True)
    password = models.CharField(max_length=100,)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_groups',
        blank=True,
        help_text="The groups this user belongs to.",
        verbose_name="groups",
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_permissions',
        blank=True,
        help_text="Specific permissions for this user.",
        verbose_name="user permissions",
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.username


class Follow(models.Model):
    follower = models.ForeignKey('User',on_delete=models.CASCADE,related_name='following',)
    following = models.ForeignKey('User',on_delete=models.CASCADE,related_name='followers',)
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('follower','following')

    def __str__(self):
        return f'{self.follower}-->{self.following}'

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError



class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        user.set_password(password)
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    login = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': "email або username"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': "password"})
    )

    def clean(self):
        cleaned_data = super().clean()
        login_input = cleaned_data.get("login")
        password = cleaned_data.get("password")
        user = authenticate(username=login_input, password=password)
        if user is None:
            raise ValidationError('невірний username/email  або пароль')
        self.user = user
        return cleaned_data

accounts/views.py
from .forms import UserRegistrationForm, LoginForm
from django.contrib.auth import login
from django.contrib import messages

from django.shortcuts import render, redirect


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.user
            login(request, user)
            messages.success(request, "Ви успішно Увійшли!")
            return redirect('user:profile',username=user.username)
        else: messages.error(request, "Помилка")
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})



def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created!')
            return redirect('accounts:login')
        else:
            messages.error(request, "Помилка!")
    else:
        form = UserRegistrationForm()
    return render(request, "accounts/register.html", {"form": form})

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Login</title>
    <link rel="stylesheet" href="{% static 'login_styles.css' %}">
</head>
<body>
    <div class="login-container">
        <h1>Instagram</h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="alert alert-{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'accounts:login'%}" method="POST">
            {% csrf_token %}
            {{ form.login.label_tag }} {{ form.login }}
            {{ form.password.label_tag }} {{ form.password }}

            <button type="submit">Увійти</button>
        </form>
        <div class="or">АБО</div>
<!--        <a href="/facebook-login" class="facebook-login">Увійти через Facebook</a>-->
<!--        <p><a href="/forgot-password">Забули пароль?</a></p>-->
        <div class="signup">
            Не маєте облікового запису? <a href="{% url 'accounts:register'%}">Зареєструйтеся</a>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Login</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Instagram</h1>
        <button class="button-facebook">Увійти через Facebook</button>
        <div class="separator">
            <div></div>
            <span>АБО</span>
            <div></div>
        </div>
        <form action="{% url 'accounts:register'%}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="submit-button">Зареєструватися</button>
        </form>
        <p>
        <div class="signup">
            У вас є обліковий запис? <a href="{% url 'accounts:login'%}">login</a>
        </div>
        <p>
        <p class="info-text">
            Люди, які користуються нашим сервісом, могли завантажити вашу контактну інформацію в Instagram. <a href="#">Докладніше</a>.
        </p>
        <p class="info-text">
            Реєструючись, ви приймаєте наші <a href="#">Умови</a>, <a href="#">Політику конфіденційності</a> і <a href="#">Політику щодо файлів cookie</a>.
        </p>
    </div>
</body>
</html>