post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('',views.home_view,name='home'),
    path('create/',views.create_post,name='create_post'),
    path('like/<int:post_pk>/', views.like_post_ajax,name='like_post_ajax'),
]

src/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('user/', include('user.urls')),
    path('posts/', include('post.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('<str:username>/',views.profile_view,name='profile'),
    path('<str:username>/edit/',views.edit_profile_view,name='edit_profile')
]

post/models.py
from django.db import models
from django.conf import settings



class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,related_name='posts')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    caption = models.CharField(max_length=500)

    def __str__(self):
        return f'Post by {self.author.username}'

    @property
    def likes(self):
        return [like.user for like in self.like_set.all()]


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE,related_name='likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('post','user')
    def __str__(self):
        return f'Like by {self.user.username} on post_id {self.post.id}'


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


class Image(models.Model):
    image = models.ImageField(upload_to='posts/')
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name="images")

    def __str__(self):
        return f'image for post_id {self.post.id}'


class PostTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name="post_tags")
    tag = models.ForeignKey('Tag', on_delete=models.CASCADE, related_name="post_tags")



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.content[:20]}'

post/forms.py
from .models import Post, Tag, PostTag, Image
from django import forms
from .models import Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['caption']


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']


class PostForm(forms.ModelForm):
    tags = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'Введіть теги через кому, напр. "travel, food, sunset"',
            'class': 'comment-input'
        })
    )

    class Meta:
        model = Post
        fields = ['caption']



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.TextInput(attrs={
                'placeholder': 'Напиши коментар...',
                'class': 'comment-input',
            })
        }

post/views.py
from .models import Post, Like, Tag, PostTag
from django.shortcuts import render, redirect
from .forms import PostForm, ImageForm, CommentForm
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Post, Like


# Create your views here.geю

@login_required
def home_view(request):
    posts = Post.objects.all().prefetch_related('images', 'comments', 'post_tags')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            post_id = request.POST.get('post_id')
            post = get_object_or_404(Post, id=post_id)
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('post:home')
    else:
        comment_form = CommentForm()

    return render(request, 'post/home.html', {
        'posts': posts,
        'comment_form': comment_form,
    })


def create_post(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        image_form = ImageForm(request.POST, request.FILES)
        if post_form.is_valid() and image_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()

            # Збереження тегів
            tag_string = post_form.cleaned_data.get('tags', '')
            tag_names = [t.strip() for t in tag_string.split(',') if t.strip()]
            for name in tag_names:
                tag, _ = Tag.objects.get_or_create(name=name.lower())
                PostTag.objects.create(post=post, tag=tag)

            # Збереження зображення
            image = image_form.save(commit=False)
            image.post = post
            image.save()

            return redirect('post:home')
    else:
        post_form = PostForm()
        image_form = ImageForm()
    return render(request, 'post/create_post.html', {
        'post_form': post_form,
        'image_form': image_form
    })



#
# @require_POST
# @login_required
# def like_post(request):
#     post_id = request.POST.get('post_id')
#     try:
#         post = Post.objects.get(id=post_id)
#     except Post.DoesNotExist:
#         return JsonResponse({'error': 'Пост не знайдено'}, status=404)
#
#     liked = Like.objects.filter(user=request.user, post=post)
#     if liked.exists():
#         liked.delete()
#         is_liked = False
#     else:
#         Like.objects.create(user=request.user, post=post)
#         is_liked = True
#
#     return JsonResponse({
#         'liked': is_liked,
#         'likes_count': post.like_set.count()
#     })


@login_required
@require_POST
def like_post_ajax(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    like, created = Like.objects.get_or_create(post=post, user= request.user)
    if not created:
        like.delete()
        is_liked = False
        print('like is delete',f'{is_liked=}')
    else:
        is_liked = True
        print('like is created',f'{is_liked=}')
    return JsonResponse({
        "is_liked": is_liked,
        "likes_count": post.likes.count()
    })

post/templates/post/create_post.html
<!--<form method="POST" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    {{ post_form.as_p }}-->
<!--    {{ image_form.as_p }}-->
<!--    <button type="submit">Створити пост</button>-->
<!--</form>-->

{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <title>Створити пост</title>
  <link rel="stylesheet" href="{% static 'styles_home.css' %}">
</head>
<body>
  <!-- 🔍 Навігаційна панель -->
  <div class="sidebar">
    <ul>
      <li><a href="{% url 'post:home' %}"><img src="{% static 'img/home.svg' %}" alt="home"> Головна</a></li>
      <li><a href="{% url 'post:create_post' %}"><img src="{% static 'img/search.svg' %}" alt="search"> Пошук</a></li>
      <li><a href="{% url 'post:create_post' %}"><img src="{% static 'img/notify.svg' %}" alt="notify"> Сповіщення</a></li>
      <li><a href="{% url 'post:create_post' %}"><img src="{% static 'img/plus.svg' %}" alt="create"> Створити</a></li>
      <li><a href="{% url 'user:profile' request.user.username %}"><img src="{% static 'img/user.svg' %}" alt="profile"> Профіль</a></li>
    </ul>
  </div>

  <!-- 📝 Форма створення поста -->
  <div class="feed-container">
    <div class="post-card">
      <div class="post-header">
        <h2 style="margin: 0;">Новий пост</h2>
      </div>

      <form method="POST" enctype="multipart/form-data" style="padding: 20px;">
        {% csrf_token %}
        <div style="display: flex; flex-direction: column; gap: 16px;">
          {{ post_form.caption.label_tag }}
          {{ post_form.caption }}

          {{ post_form.tags.label_tag }}
          {{ post_form.tags }}

          {{ image_form.image.label_tag }}
          {{ image_form.image }}
        </div>

        <button type="submit" class="like-btn" style="margin-top: 20px;">Створити пост</button>
      </form>
    </div>
  </div>
</body>
</html>

post/templates/post/home.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <title>Головна</title>
  <link rel="stylesheet" href="{% static 'styles_home.css' %}">
</head>
<body>

  <!-- 🧭 Ліва навігаційна панель -->
  <div class="sidebar">
    <ul>
      <li><a href="{% url 'post:home' %}"><img src="{% static 'img/home.svg' %}" alt="home"> Головна</a></li>
      <li><a href="{% url 'post:create_post' %}"><img src="{% static 'img/search.svg' %}" alt="search"> Пошук</a></li>
      <li><a href="{% url 'post:create_post' %}"><img src="{% static 'img/notify.svg' %}" alt="notify"> Сповіщення</a></li>
      <li><a href="{% url 'post:create_post' %}"><img src="{% static 'img/plus.svg' %}" alt="create"> Створити</a></li>
      <li><a href="{% url 'user:profile' request.user.username %}"><img src="{% static 'img/user.svg' %}" alt="profile"> Профіль</a></li>
    </ul>
  </div>

  <!-- 📜 Стрічка дописів -->
  <div class="feed-container">
    {% for post in posts %}
      <div class="post-card">

        <!-- 👤 Автор -->
        <div class="post-header">
          <img src="{% static 'img/default_avatar.png' %}" class="avatar" alt="avatar">
          <span class="username">{{ post.author.username }}</span>
        </div>

        <!-- 🖼️ Зображення -->
        {% if post.images.all %}
        <div class="post-images">
          {% for image in post.images.all %}
            <img src="{{ image.image.url }}" class="post-image" alt="post image">
          {% endfor %}
        </div>
        {% endif %}


        <div id="like-container-{{ post.id }}">
  <button type="button" data-url="{% url 'post:like_post_ajax' post.id %}" id="like-btn-{{ post.id }}">
  {% if post.is_liked  %}
      ❤
    {% else %}
      ❤️
    {% endif %}
  </button>
  <span id="like-count-{{ post.id }}">{{ post.likes.count }}</span> лайків
</div>


        <!-- ✍️ Підпис -->
        <div class="caption">
          <strong>{{ post.author.username }}</strong> {{ post.caption }}
        </div>

        <!-- 🏷️ Теги -->
        {% if post.post_tags.all %}
        <div class="tags">
          {% for tag in post.post_tags.all %}
            <span class="tag">#{{ tag.tag.name }}</span>
          {% endfor %}
        </div>
        {% endif %}

        <!-- 💬 Коментарі -->
        <div class="comments">
          {% for comment in post.comments.all %}
            <div class="comment">
              <strong>{{ comment.user.username }}</strong>: {{ comment.content }}
            </div>
          {% empty %}
            <div class="comment-empty">Ще ніхто не прокоментував 🙈</div>
          {% endfor %}
        </div>

        <!-- 📝 Форма коментарів -->
        <form method="POST" class="comment-form">
          {% csrf_token %}
          <input type="hidden" name="post_id" value="{{ post.id }}">
          {{ comment_form.content }}
          <button type="submit" class="comment-submit">Надіслати</button>
        </form>

      </div>
    {% endfor %}
  </div>

  <!-- 🔗 JavaScript -->
<script>
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== "") {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

document.querySelectorAll('[id^="like-btn-"]').forEach(function(btn) {
    btn.addEventListener('click', function() {
        const url = btn.getAttribute('data-url');
        fetch(url, {
            method: 'POST',
            headers: {
                'X-CSRFToken': getCookie('csrftoken'),
                'X-Requested-With': 'XMLHttpRequest',
            },
        })
        .then(response => response.json())
        .then(data => {
            btn.textContent = data.is_liked ? '❤' : '❤️';
            const postId = btn.id.split('-')[2];
            document.getElementById('like-count-' + postId).textContent = data.likes_count;
        })
        .catch(error => {
            alert("Помилка при відправці лайку");
        });
    });
});
</script>

</body>
</html>